### PR TITLE
completed the input components

### PR DESCRIPTION
**Pull request by sohan9819**
Done making the input text and radio component  and added the code snippets to the docs

### CODE REVIEW

**Review by vikrantkode — COMMENTED** [review]
All Looks good to me

**Comment by vikrantkode** [comment]
> All Looks good to me

UI is awesome

**Comment by sohan9819** [comment]
> > All Looks good to me
> 
> UI is awesome

Thanks bro

**Review by bmendhe23 — APPROVED** [review]
Looks good to merge.

**Pull request merged**
