### PR TITLE
refactored badge position values

### PR DESCRIPTION
**Pull request by sohan9819**
changed the position value , border-radius and sizes of badges

### CODE REVIEW

**Review by harshitpaliwal95 — COMMENTED** [review]
side bar is not working

**Comment by harshitpaliwal95** [comment]
overall looks good

**Comment by sohan9819** [comment]
> side bar is not working

bro the entire website is completed already  i am making a second pr from this branch so its showing the old version of the site any idea how to fix it

**Review by sumitch29 — APPROVED** [review]
Good to go.

**Pull request merged**
