### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by sohan9819**
My first pr for main . Done making the setup and added some basic utility classes .
Here is my file structure .
 .
├── alpha
├── assets
│   └── images
├── css
│   └── fonts
├── documentation
│   └── pages
├── js 
└──sass
      ├── abstracts
      ├── base
      ├── components
      ├── layout
      └── pages
      
alpha

docs-page

### CODE REVIEW

**Review by Pratham82 — COMMENTED** [review]
Just a suggestion, align headings to the left. Rest looks good. And deploy the site to netflify, so we review the live preview.

**Review by sakshi006 — COMMENTED** [review]
good to go.

**Comment by sohan9819** [comment]
@Pratham82 sure bro .

**Comment by sakshi006** [comment]
Looks good.

**Comment by TusharJade** [comment]
Great design it responsive too, great work bro👌

**Comment by sohan9819** [comment]
@TusharJade thanks bro

**Pull request merged**
