### PR TITLE
added floating button and some spacing between sections

### PR DESCRIPTION
**Pull request by sohan9819**
Added a floating action button to navigate between sections in mobile screens . Also added a preloader to the page .

image

### CODE REVIEW

**Review by raieegulhane — COMMENTED** [review]
Personal suggestion:
In preview the page looks cluttered when the menu box is open. Suggestion: Blur the background to that the menu box is in focus. 
Rest looks good

**Comment by sohan9819** [comment]
> Personal suggestion: In preview the page looks cluttered when the menu box is open. Suggestion: Blur the background to that the menu box is in focus. Rest looks good

Thanks for the suggestions will work on it 👍

**Review by Rutwik87 — APPROVED** [review]
good to merge

**Comment by rahul31agrawal** [comment]
Looks good to merge

**Pull request merged**
