### PR TITLE
added floating action button to buttons

### PR DESCRIPTION
**Pull request by sohan9819**
added a floating action button in my buttons section 

image

### CODE REVIEW

**Review by Rutwik87 — APPROVED** [review]
Good to go

**Review by teja538 — COMMENTED** [review]
looks good, small suggestion: use rems instead of px

**Comment by sohan9819** [comment]
> looks good, small suggestion: use rems instead of px

Thanks for the suggestions . I worked on it 👍.

**Comment by rahul31agrawal** [comment]
Looks good to me

**Pull request merged**
