### PR TITLE
added avatar class components and updated the docs for avatar

### PR DESCRIPTION
**Pull request by sohan9819**
Added avatar and badge component to the docs and the UI library

### CODE REVIEW

**Comment by sakshi006** [comment]
Hey, host your development branch on netlify, it would be easy that way for us to review. Or, put some screenshots of your page.

**Comment by sohan9819** [comment]
I have hosted the dev branch and this branch is made with dev as base .Still it's not showing the preview . Any idea ?

**Review by sakshi006 — APPROVED** [review]
Good to go.

**Review by Pratham82 — COMMENTED** [review]
Looks good to me

**Pull request merged**
